// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASz8cuJIbTpSgivOp24E7yG3om_PbKJ_w',
    appId: '1:909567125019:web:5a0c131898d2a207ef3abe',
    messagingSenderId: '909567125019',
    projectId: 'systeme-f5b30',
    authDomain: 'systeme-f5b30.firebaseapp.com',
    storageBucket: 'systeme-f5b30.appspot.com',
    measurementId: 'G-TGSGSYG7D7',
    databaseURL: 'https://systeme-f5b30-default-rtdb.firebaseio.com/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7qwZ-gjTalzxfOUXAzOI8dkjHRPUhu3Y',
    appId: '1:909567125019:android:e1309e79f0e200eaef3abe',
    messagingSenderId: '909567125019',
    projectId: 'systeme-f5b30',
    storageBucket: 'systeme-f5b30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXQybw0G3D2PYcRaZQZNQ952VglQ9aPlQ',
    appId: '1:909567125019:ios:f039c02cb599a8a6ef3abe',
    messagingSenderId: '909567125019',
    projectId: 'systeme-f5b30',
    storageBucket: 'systeme-f5b30.appspot.com',
    iosClientId: '909567125019-1lr0u19dhejo1m3g0c40g8nndjjln6eg.apps.googleusercontent.com',
    iosBundleId: 'com.example.systemedarosage',
  );
}
